server.default_listen_address=0.0.0.0
server.bolt.listen_address=:7687
server.http.listen_address=:7474
server.https.enabled=false
dbms.security.auth_enabled=false
dbms.security.procedures.unrestricted=gds.*
server.memory.heap.initial_size=2G
server.memory.heap.max_size=2G
server.memory.pagecache.size=512M
dbms.usage_report.enabled=false
db.transaction.timeout=0s
